name = "fariha-portfolio"
type = "webpack"  # or remove if you're not using a bundler
account_id = "75b137055d9d3f0df4ad70c77bdc34"
zone_id = "32f9bc549c606a96fbf8c8e2f7721f12"
compatibility_date = "2025-07-07"

[site]
bucket = "html5up-highlights-fariha"

# Optional for custom domain
# route = "https://www.fariha-portfolio.com/*"

[observability.logs]
enabled = false
